// data/speakerData.ts
  
  const speakerData = [
    {
      imgSrc: '../img/speakers/rTill.png',
      name: 'Till Kamppeter',
      title: 'Leader OpenPrinting\nLinux Foundation Fellow',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Aveek Basu.jpeg',
      name: 'Aveek Basu',
      title: 'Org Admin - The Linux Foundation GSoC projects\nCommunity & Program Manager OpenPrinting, Zephyr Ambassador',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Michael Sweet.png',
      name: 'Micheal R. Sweet',
      title: 'Creator of CUPS',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Pierre Clisson.jpeg',
      name: 'Pierre Clisson',
      title: 'Creator of Timeflux',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Oliver Völckers.jpg',
      name: 'Oliver Völckers',
      title: 'Founder, BeST Berliner Sensortechnik GmbH',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Manuel Haro.jpg',
      name: 'Manuel Haro',
      title: 'Professor at the Autonomous University of Zacatecas\nFounder of the Free Software Laboratory of Zacatecas\nLeader of the Open Source Innovation Labs Network',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Jonas Remmert.jpg',
      name: 'Jonas Remmert',
      title: 'Embedded Systems Engineer at PHYTEC Messtechnik GmbH',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    
    {
      imgSrc: '../img/speakers/Jiongchi Yu.png',
      name: 'Jiongchi Yu',
      title: 'GSoC contributor for OpenPrinting\nOSS-Fuzz testing for CUPS and other OpenPrinting components',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/George Andrei.jpg',
      name: 'George-Andrei Iosif',
      title: 'Working with Software Security\nOSS-Fuzz and fuzz testing',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/RaghavendraS.jpg',
      name: 'Raghavendra Sirigeri',
      title: 'Working on Questodev\nA pioneer of cloud-native tech',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Paritoshik Paul.jpg',
      name: 'Paritoshik Paul',
      title: 'Technical Lead at Srijan Technologies\nPassionate Drupal Enthusiast',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Divya Mohan.jpg',
      name: 'Divya Mohan',
      title: 'Principal Technology Advocate at SUSE\nRegional lead in the CHAOSS project\nco-creator of the KCNA exam',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Ayush Chopra.jpg',
      name: 'Ayush Chopra',
      title: 'MIT Media Lab',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Subrata Banik.jpg',
      name: 'Subrata Banik',
      title: 'Technical Staff Member at Google\nFirmware Engineer',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Utkarsh Bhatt.jpg',
      name: 'Utkarsh Bhatt',
      title: 'Software Engineer in the Ceph Engineering team\nSoftware Engineer at Canonical',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Dhruva Gole.jpg',
      name: 'Dhruva Gole',
      title: 'Embedded Linux Engineer at Texas Instuments\nOSS-Fuzz and fuzz testing',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Anindya Kundu.jpg',
      name: 'Anindya Kundu',
      title: 'Developer at Sugar Labs\nSoftware Engineer at Sorcero',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Abhigyan Ghosh.jpg',
      name: 'Abhigyan Ghosh',
      title: 'Software Engineer in the Ceph Engineering team at Canonical',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/rudra.jpeg',
      name: 'Rudra Saraswat',
      title: 'Creator of BlendOS\nUbuntu Unity project lead',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Gaurav Mishra.jpg',
      name: 'Gaurav Mishra',
      title: 'Researcher at Siemens',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Santosh Saptarshi.jpg',
      name: 'Santosh Saptarshi',
      title: 'Application Seurity at Netcracker Technologies',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Wajoud Noorani.jpg',
      name: 'Wajoud Noorani',
      title: 'Data scientist at Changejar',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Kaushlendra Pratap Singh.jpg',
      name: 'Kaushlendra Pratap Singh',
      title: 'Researcher at Siemens\nGSoC Mentor',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Shaheem Azmal M MD.jpg',
      name: 'Shaheem Azmal M MD',
      title: 'Researcher at Siemens',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Kiran Divekar.jpg',
      name: 'Kiran Divekar',
      title: 'R & D Engineer at Broadcom\nLinux Kernel Contributor',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Aaryan Porwal.jpg',
      name: 'Aaryan Porwal',
      title: 'Software Engineer at Canonical\nGSoC Contributor for Ceph',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Sahil Arora.jpg',
      name: 'Sahil Arora',
      title: 'Developer at Amazon\nGSoC Contributor and Mentor at Linux Foundation',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Vlad Val.png',
      name: 'Vlad Val',
      title: '',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Avinal Kumar.jpg',
      name: 'Avinal Kumar',
      title: 'Software Engineer at Red Hat\nGSoC Mentor at FOSSology',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Vandana Salve.png',
      name: 'Vandana Salve',
      title: 'Leader in Linux Kernel Engineering',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Gotam Gorabh.jpg',
      name: 'Gotam Gorabh',
      title: '',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Rudra Pratap Singhh.jpg',
      name: 'Rudra Pratap Singh',
      title: 'SWE at Tether',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Suraj Mahto.png',
      name: 'Suraj Mahto',
      title: 'SRE at Tether\nGSoC and SoK Contributor',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    
    {
      imgSrc: '../img/speakers/Sanjiban Sengupta.jpg',
      name: 'Sanjiban Sengupta',
      title: 'Contributor to CERN and Voltron Data\nCo-created Substrait Fiddle',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Ansh Arora.jpg',
      name: 'Ansh Arora',
      title: 'Program and Partnerships manager at FOSS United',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Dinesh Gehlot.jpg',
      name: 'Dinesh Gehlot',
      title: 'ChromeOS firmware team at Google',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Jayvik Desai.jpg',
      name: 'Jayvik Desai',
      title: 'ChromeOS firmware team at Google',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Pranava Y N.jpg',
      name: 'Pranava Y N',
      title: 'ChromeOS firmware team at Google',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Rishika Raj.jpg',
      name: 'Rishika Raj',
      title: 'ChromeOS firmware team at Google',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Akarshan Kapoor.jpg',
      name: 'Akarshan Kapoor',
      title: 'Ubuntu Summit Speaker\nIndian Institute of Technology Mandi',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Priyam Chakraborty.jpg',
      name: 'Priyam Chakraborty',
      title: 'Postdoctoral fellow at Complex and Biological Fluids Lab, IISc',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    
    {
      imgSrc: '../img/speakers/Deepak Khatri.jpg',
      name: 'Deepak Khatri',
      title: 'Product development engineer at BeagleBoard.org',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Rudra Pratap Singh.jpg',
      name: 'Rudra Pratap Singh',
      title: 'GSoC Contributor for The Linux Foundation\nStudent at IIT Mandi',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Deepak Patankar.jpg',
      name: 'Deepak Patankar',
      title: 'GSoC contributor and mentor at the Linux Foundation',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Shivam Jaiswal.jpg',
      name: 'Shivam Jaiswal',
      title: 'GSoC Contributor for The Linux Foundation\nStudent at IIT Mandi',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Ayush Singh.jpg',
      name: 'Ayush Singh',
      title: 'GSoC contributor under Tianocore and BeagleBoard.org',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Sibi Sankar.jpg',
      name: 'Sibi Sankar',
      title: 'Linux Kernel Engineer at Qualcomm',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Josianne Marsan.jpg',
      name: 'Josianne Marsan',
      title: 'Full Professor at Université Laval, Director CeRTIA',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Patrick Marois.jpg',
      name: 'Patrick Marois',
      title: 'Chief Technology Officer at Audit Analytics',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Lourival Vieira Neto.jpg',
      name: 'Lourival Vieira Neto',
      title: 'GSoC contributor under Tianocore and BeagleBoard.org',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    {
      imgSrc: '../img/speakers/Tushar Gupta.jpg',
      name: 'Tushar Gupta',
      title: 'Associate Software Engineer at Canonical ',
      twitterUrl: '',
      facebookUrl: '',
      linkedinUrl: '',
      googleplusUrl: '',
    },
    // Add more speakers as needed
  ];
  
  export default speakerData;
//   export type { Speaker };
// 3 pictires to be corrected